dojo.require("doh.runner");
doh.register("run.testers_FirstAutoGeneratedZoteroPluginTest", [
    function(){
        var test = new StdRhinoTest("testers_FirstAutoGeneratedZoteroPluginTest","run");
        doh.assertEqual(test.result, test.run());
    },
])
tests.run();